### ISSUE TITLE
2) Додати верхній та нижній бордер секції "advertisement"

### ISSUE THREAD

**Issue by gudzsv** [gudzsv/project-syntax-samurais-01#30]
Додати верхній та нижній `border`, прибрати зайві властивості

```css
.marquee {
        border-block: 1px solid var(--gray);  /*додає бортер аналогічно макету*/
	overflow: hidden; 
	background-color: transparent; 
	/* видалити непотрібні властивості нижче*/    
        /* font-family: 'Pridi', sans-serif; */
        /* font-weight: 600; */
        /* font-size: 34px; */
        /* text-transform: uppercase; */
}
```
