### ISSUE TITLE
3) Налаштувати стилі p(параграфа) та прибрати лишні стилі span секція "advertisement"

### ISSUE THREAD

**Issue by gudzsv** [gudzsv/project-syntax-samurais-01#31]
- _Налаштувати стилі параграфа_
#
```css
.marquee__line {
    color: var(--brown);
    font-size: 28px;
    /* font-style: normal; */  /*видалити дефолтна властивість браузера*/
    line-height: 1.14;
    letter-spacing: -0.02em; /*додати властивість згідно з макетом*/
    text-transform: uppercase;
    flex-shrink: 0;
    /* margin: 0; */ /* прибрати ця властивість є для всіх параграфів в файлі reset css*/
    /*padding: 20px 0;*/ 
    padding-block: 20px; /* можна використовувати цю властивість щоб не прописувати падінгу 2 параметра як вище*/
    min-width: 100%;
    white-space: nowrap;
    animation-name: marqueeLine;
    animation-duration: 10s; /*збільшити до 10 секунд щоб не мерехтіло в очах*/
    animation-timing-function: linear; /* ease-in-out  змінити на linear як на мене краще буде якщо буде бігти строка плавно*/
    animation-iteration-count: infinite;
}
``` 

- _Прибрати всі властивості крім кольору, властивості наслідуються від батьківсього тега параграф класа_ `marquee__line`

```css
.photography {
    color: var(--white);
    /* font-size: 28px; */
    /* font-style: normal; */
    /* line-height: 1.14; */
    /* text-transform: uppercase; */
}
```
