### ISSUE TITLE
4) Додати адаптив для секції  "advertisement"

### ISSUE THREAD

**Issue by gudzsv** [gudzsv/project-syntax-samurais-01#32]
## Додати медіаправила щоб шрифт і падінг змінювався в залежності від типу девайса

```css
/* Tablet */
@media only screen and (min-width: 768px) {
.marquee__line {
    padding-block: 24px;
	font-size: 40px;
	line-height: 1.25; 
	}
}

/* Desktop - Big Desktop*/
@media only screen and (min-width: 1280px) {
.marquee__line {
	font-size: 59px;
	line-height: 1.08; 
	}
}
```
