### ISSUE TITLE
Footer прибрати бордер кнопки GO

### ISSUE THREAD

**Issue by gudzsv** [gudzsv/project-syntax-samurais-01#41]
Footer прибрати бордер кнопки `GO`

![image](https://github.com/gudzsv/project-syntax-samurais-01/assets/49489543/67d3d167-f7da-4a5b-a769-a63d556a4d90)

Має бути так 

![image](https://github.com/gudzsv/project-syntax-samurais-01/assets/49489543/6c719e7d-5584-479a-9acb-4f9742030188)

```css
.footer-btn {
    color: var(--white);
    text-align: center;
    /* font-family: DM Sans; */ /*можна прибрати має насслідуватись з боді*/
    font-size: 20px;
    /* font-style: normal; */ /*можна прибрати це дефолтний параметр браузера*/
    /* font-weight: 400; */ /*можна прибрати це дефолтна товщина шрифта браузера*/
    line-height: 1.2;
    width: 60px;
    height: 60px;
    flex-shrink: 0;
    border-radius: 12px;
    border: none;  /*додати властивість щоб прибрати рамку з кнопки*/
    background-color: var(--fill);
}
```
