### ISSUE TITLE
Footer змінити Input щоб вміщався в розміри екрану 320px та прибрати бордер інпуту

### ISSUE THREAD

**Issue by gudzsv** [gudzsv/project-syntax-samurais-01#42]
## Footer змінити Input щоб вміщався в розміри екрану 320px

**_Зараз_** 

![image](https://github.com/gudzsv/project-syntax-samurais-01/assets/49489543/c57e470e-9bb6-4458-9e9b-3e4e634688df)

**_Має бути_** 

![image](https://github.com/gudzsv/project-syntax-samurais-01/assets/49489543/512332bf-0186-4576-b676-c59ef32300f4)

Плтрібно змінити наступні стилі нижче

1) Стилі інпуту

```css
.footer-input {
    display: inline-block;
    color: var(--black);
    font-family: DM Sans; /*можна прибрати має насслідуватись з боді*/
    font-size: 16px; /*можна прибрати це дефолтний шрифт браузера*/
    font-style: normal;  /*можна прибрати це дефолтний параметр браузера*/
    font-weight: 400; /*можна прибрати це дефолтна товщина шрифта браузера*/
    line-height: 1.25;
    max-width: 267px; /*додати щоб тягнулось максимум до величини що на макеті*/
    width: 100%; /*змінити на 100%*/
    height: 60px;
    flex-shrink: 0; /*можна прибрати так як елемент не являеться флекс елементом*/
    border-radius: 12px;
    background-color: var(--white);
	border: none; /*додати властивість щоб прибрати рамку з інпута*/
    padding-left: 18px;
}
``` 

2) Для лейбла задати ширину 100% або прибрати його з HTML

```css
.footer-label {
    width: 100%;
}
``` 

3) в блоці footer-interaction прибрати властивість align-items: flex-start; щоб інпіт розтягнувся по ширині

```css
.footer-interaction {
    display: flex;
    flex-direction: column;
    /* align-items: flex-start; */
    margin-bottom: 40px;
}
```
