### ISSUE TITLE
Footer вирівняти логотип по лівому краю при зміні розміру на Tablet і більше 

### ISSUE THREAD

**Issue by gudzsv** [gudzsv/project-syntax-samurais-01#44]
## Footer вирівняти логотип по лівому краю при зміні розміру на Tablet і більше 

**_Зараз_**

![image](https://github.com/gudzsv/project-syntax-samurais-01/assets/49489543/32c8bed7-08d8-426e-b085-a6fdb72b816f)

**_Має бути_**

![image](https://github.com/gudzsv/project-syntax-samurais-01/assets/49489543/baec1bdf-eb87-4d7a-87a2-14371460dbb8)

**Потрібно прописати наступні властивості**

```css
@media only screen and (min-width: 768px){
  .foot-logo-icon {
      max-width: 123px;
      width: auto;
      height: 16px;
  }
}
``` 

**логотип буде мати вигляд**

![image](https://github.com/gudzsv/project-syntax-samurais-01/assets/49489543/1f50afdc-b260-46ca-a28c-e68d0f5b335b)
