### ISSUE TITLE
Mentors - змінити розташування менторів

### ISSUE THREAD

**Issue by gudzsv** [gudzsv/project-syntax-samurais-01#47]
## Mentors - змінити розташування менторів _(не потрібно притискати менторів до країв контейнера згідно [макету](https://www.figma.com/file/nYhJLmpVv9oTal8XBYfPdT/FocusFrame-2.0-(Copy)?node-id=86%3A599&mode=dev))_

Потрібно прибрати в класі нижчае властивість` justify-content: space-between;`

```css
@media screen and (min-width: 1024px)
.mentors-list {
    display: flex;
    /* justify-content: space-between; */
}
```
