### ISSUE TITLE
Mentors Прибрати верхній падінг у тега li  перенести відступ на h2

### ISSUE THREAD

**Issue by gudzsv** [gudzsv/project-syntax-samurais-01#49]
## Mentors Прибрати верхній падінг у тега` li`  перенести відступ на `h2` так легше керувати відступом від заголовку

Прибрати `padding-top` у елемента `li`

```css
.mentors-list-items {
    padding-top: 40px;
}
``` 
Прибрати падінг в медіаправил також прибрати властивості які закоментовані

```css
@media screen and (min-width: 768px){
.mentors-list {
    /* margin-left: auto; */ 
    /* margin-right: auto; */
    /* padding-top: 50px; */
    display: flex;
    flex-wrap: wrap;
    gap: 93px 100px;
    justify-content: center;
}
}
``` 

Додати до h2

```css
.mentors-title {
    margin-bottom: 40px;
}
``` 

Додати медіаправило для заголовка h2 

```css
@media screen and (min-width: 768px) {
.mentors-title {
    margin-bottom: 50px;
}
}
```
