### ISSUE TITLE
Mentors Відображення менторів згідно з макетом (в центрі контейнера)

### ISSUE THREAD

**Issue by gudzsv** [gudzsv/project-syntax-samurais-01#50]
## Mentors Відображення менторів згідно з макетом (в центрі контейнера)

**Мбільна версія відступи між `li `зроби таким чином**

```css
.mentors-list-items + .mentors-list-items {
  margin-top: 40px;
}
``` 

Для **Tablet** 

```css
@media screen and (min-width: 768px) {
  /*обнуляєм відступ для мобілки*/
  .mentors-list-items + .mentors-list-items {
    margin-top: 0;
  }
  
  .mentors-list {
       /* прибери влістивості що закоментовані*/
      /* margin-left: auto; */
      /* margin-right: auto; */
      /* padding-top: 50px; */
      display: flex;
      flex-wrap: wrap;
      gap: 93px 100px;
      justify-content: center;
  }

}
``` 

тут зміни крок з `1024px` на `1280px`

```css
@media screen and (min-width: 1024px){
  .mentors-list {
      gap: 100px; /*додати властивість*/
      /* display: flex; */ /*прибери  властивість так як вона наслідується з попереднього медіаправила  з 768px*/
      /* justify-content: space-between; */ /*прибери властивість карточки мають прижиматись до центру*/
  }
}
```
